---
abstract: 'framework for remote system introspection'
author:
  - 'Robert Sedlacek <r.sedlacek@shadowcat.co.uk>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: System-Introspector
no_index:
  directory:
    - t
    - inc
requires:
  Capture::Tiny: 0.12
  Config::General: 0
  Data::YAML::Writer: 0
  Digest::SHA: 0
  File::Basename: 0
  File::Path: 0
  File::Tree::Snapshot: 0
  Getopt::Long: 0
  IPC::Run: 0
  JSON::Diffable: 0
  Module::Metadata: 0
  Module::Runtime: 0
  Moo: 0.009013
  Object::Remote: 0
  Object::Remote::Future: 0
  Pod::Usage: 0
  strictures: 1
version: 0.001_001
